# Generated by Django 5.1.4 on 2024-12-18 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_category_description_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
    ]
